### ISSUE TITLE
about focal loss  mentioned in the paper

### ISSUE THREAD

**Issue by iDonal** [codefuse-ai/MFTCoder#10]
I couldn't find any function or hyper-parameters related to focal loss and FAMO in the code, as mentioned in the paper.

so , the code below is outdated？
https://github.com/codefuse-ai/MFTCoder/blob/main/mft_peft_hf/src/utils/auto_accelerate_utils.py

**Comment by twelveand0** [comment]
Hello, thanks for your attention. We haven't submitted this portion of the code to GitHub yet.  Next, we will update FAMO loss-related.
