### ISSUE TITLE
data.helper 无法加载？

### ISSUE THREAD

**Issue by liudonglei** [codefuse-ai/MFTCoder#11]
data.helper 无法加载？

[Global Rank 0] open file /DDD/CodeExercise-Python-27k/CodeExercise-Python-27k.jsonl
[Global Rank 0]shape of cur train dataset: (4116, 4097)
[Global Rank 0]shape of cur valid dataset: (216, 4097)
[Global Rank 0]num tokens: [14803925]
[Global Rank 0]effective token rate: [0.8343119810602782]
> train loss weights in rank 0: [1.0]
> valid loss weights in rank 0: [1.0]
> common denomination factor for CE loss in rank 0: 1
> train sample weights in rank 0: [1.0]
> valid sample weights in rank 0: [1.0]
> global train num in rank 0: 4116
> global valid num in rank 0: 216
loss weight of train dataset 0 before update in rank 0: 95.0
loss weight of train dataset 0 after update in rank 0: 1.0
Traceback (most recent call last):
  File "/DDD/MFTCoder/mft_peft_hf/src/pefts/mft_accelerate.py", line 382, in <module>
    main()
  File "/DDD/MFTCoder/mft_peft_hf/src/pefts/mft_accelerate.py", line 246, in main
    train_dataset, valid_dataset = load_dataset_from_jsonl(args, shard_data=True, world_size=args.world_size,
  File "/DDD/MFTCoder/mft_peft_hf/src/pefts/../data/gpt2_multi_task_dataset.py", line 343, in load_dataset_from_jsonl
    blending_train_dataset = GPT2BlendableDataset(all_train_datasets, train_sample_weights, global_train_num, local_train_num)
  File "/DDD/MFTCoder/mft_peft_hf/src/pefts/../data/gpt2_multi_task_dataset.py", line 105, in __init__
    from data import helpers
ImportError: cannot import name 'helpers' from 'data' (/DDD/MFTCoder/mft_peft_hf/src/pefts/../data/__init__.py)

**Comment by chencyudel** [comment]
Make sure you have [helpers.cpython-38-x86_64-linux-gnu.so](https://github.com/codefuse-ai/MFTCoder/blob/main/mft_peft_hf/src/data/helpers.cpython-38-x86_64-linux-gnu.so) and make sure your import path is correct. 
And this works for x86_64, if not, we are going to add compile tools later.

**Comment by ymwang-2020** [comment]
请问您解决了吗？我也遇到了同样的问题

**Comment by ymwang-2020** [comment]
> 请问您解决了吗？我也遇到了同样的问题

找到问题所在了，python版本不对应，只能为3.8

**Comment by liudonglei** [comment]
你得使用cmake 编译一下helper.cpp文件为对应的.so文件，你百度一下如何编译cpp



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月05日 21:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [codefuse-ai/MFTCoder] data.helper 无法加载？ (Issue #11) |

请问您解决了吗？我也遇到了同样的问题

找到问题所在了，python版本不对应，只能为3.8
