### ISSUE TITLE
请问FSDP的训练API啥时候会开源出来

### ISSUE THREAD

**Issue by peiji1981** [codefuse-ai/MFTCoder#14]
请问FSDP的训练API啥时候会开源出来

**Comment by chencyudel** [comment]
@peiji1981 We are going to release MFTCoder v0.3.0 in Jan/24, in which new MFTCoder-accelerate is going to support FSDP as an alternative option besides DeepSpeed. It is not as stable as DeepSpeed, however it would be a good try for using FSDP on Full-parameters Fine-tuning.
