### ISSUE TITLE
Inquiry about weighted_loss_mode

### ISSUE THREAD

**Issue by tszdanger** [codefuse-ai/MFTCoder#15]
Hello,

First of all, I would like to thank you for your great contribution to the community. I have a question regarding the "weighted_loss_mode" in your repository.

The reason for my inquiry is that I encountered some issues when trying to switch from the default "case3" to "case1". I am not entirely sure if "case1/2/3/4" correspond to the four types of loss mentioned in the paper.

I would greatly appreciate it if you could provide me with more information on this matter. Additionally, if there are any issues related to "use before assign" in "case1" and "case2", I would be more than happy to create a PR to merge the changes.

Thank you for your time and help.

BTW, I really enjoy reading your code, it is one of the most clear one that I ever met in this community.

Best regards, 
Zonkey.

**Comment by wj882018** [comment]
First of all,"case1/2/3/4" is not correspond to the four types of loss mentioned in the paper.
Here are the means of "case1/2/3/4":
case1: Average loss of all tokens within a single batch in its most original form.
case2: Balanced lengths of all samples within a batch.
case3: Balanced data distribution among tasks within a batch.
case4: Combination of balanced lengths and data distribution within a batch.
Thank you for your attention.
