### ISSUE TITLE
请问，对模型进行多任务微调该怎么设计jsonl数据集？

### ISSUE THREAD

**Issue by a793181018** [codefuse-ai/MFTCoder#16]
如题，
通过定义jsonl数据格式中的role字段的值来新增标签，从而实现多任务的应答吗

**Comment by twelveand0** [comment]
你好，有以下几点
（1）目前MFTCoder只支持human/bot/system三种角色标签，无法通过扩展角色标签来实现多任务
（2）实现多任务，您可以通过在```mft_peft_hf/src/pefts/config/config.json```文件中配置**data_paths**参数值实现，例如三个任务可以这样配置
```
data_paths": "[/path/to/task_1/data/,/path/to/task_2/data,/path/to/task_3/data]
```
请将```/path/to/task_1/data/```和```/path/to/task_2/data/```替换为你的任务1和任务2 jsonl数据所在的路径

**Comment by a793181018** [comment]
那么只能为每一个任务微调出一个Lora权重咯？
根据不同的任务加载不同的Lora模型咯？

**Comment by twelveand0** [comment]
目前的多任务含义是一个模型支持多个下游任务，即同时为多个任务微调出同一个lora
你说的multi-lora的概念我们也在探索中

**Comment by a793181018** [comment]
通过system标签的内容来实现多任务切换吗

**Comment by twelveand0** [comment]
任务切换可以通过不同的system prompt实现，也可以只通过user prompt实现，多任务对system prompt设计没有特殊的要求。例如，可以训练2个任务，一个是bug fix，一个unittest，训练完成后使用时，可以仅通过不同的询问prompt实现，例如“请帮助修复下面代码中的Bug”，“请为这段python代码编写单测用例”。如果对区分任务有明确的场景需求，可以通过为每个任务设计不同的system prompt来强区分。如果对任务没有强区分需求，你可以将多任务训练出的模型视作普通的LLM看待。
