### ISSUE TITLE
国内下载方式

### ISSUE THREAD

**Issue by wuyihz** [codefuse-ai/MFTCoder#2]
国内有下载的方法吗？ Download files in China?

**Comment by ss41979310** [comment]
如果在中国境内，可以优先从魔搭平台下载模型和数据文件，从Gitee平台下载代码仓库，我们已经将文件同步到这两个站点的CodeFuse-ai组织下。

We uploaded models and dataset files to ModelScope and code repos to Gitee, both under organization CodeFuse-ai.
