### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by zzb2019053515** [codefuse-ai/MFTCoder#20]
![image](https://github.com/codefuse-ai/MFTCoder/assets/103801603/2e3b23e8-0027-4aae-8af9-6f373925125e)
How to solve this problem

**Comment by twelveand0** [comment]
I'm not certain if the model files you downloaded are corrupted. Could you please verify the data integrity of the file first? You can use a tool like sha256sum for this purpose.

**Comment by twelveand0** [comment]
This problem often occurs when the downloaded model is corrupted. This can be caused when cloning a model but git-lfs had not been installed. Please make sure ```git-lfs``` has been successfully installed by running this in your terminal:
```bash
git lfs version
```

**Comment by twelveand0** [comment]
I noticed that you haven't followed up further, so I assume you've probably resolved the issue. I will close this issue, but you can reopen it if you have more questions.
