### ISSUE TITLE
little bug fix meet

### ISSUE THREAD

**Issue by elcky** [codefuse-ai/MFTCoder#21]
1. MFTCoder/mft_peft_hf/src/pefts/run_bash.sh

raise erro to write parameter:RANK,MASTER_ADDR

I added three lines:
MASTER_ADDR=127.0.0.1

MASTER_PORT=8081

RANK=0.

2. MFTCoder/mft_peft_hf/src/data/gpt2_multi_task_dataset.py
raise erro numpy has no attribute int.

new numpy change into np.int_

**Comment by twelveand0** [comment]
Thanks for your issue and solution. Our testing is insufficient in some environments.

**Comment by twelveand0** [comment]
We will take your suggestions into our next version update. Thanks again for your advice. I will close this issue.
