### ISSUE TITLE
代码中对于3.5 Multitask Fine-Tuning with Balanced Losses的具体实现的位置（只找到了第一个loss的实现）

### ISSUE THREAD

**Issue by YanqiDai** [codefuse-ai/MFTCoder#25]
我只在mft_peft_hf/src/utils/auto_accelerate_utils.py的loss_func_mft()中找到了Balanced Losses for data imbalance (Equation 1) 的实现，请问Balanced Losses for task heterogeneity and inconsistent convergence speeds (Equation 2, 3 and 4)在代码中是否实现，如果有，在模型的训练中是如何将这四种损失结合在一起的呢？

**Comment by twelveand0** [comment]
你好，其他的均衡loss我们暂时还没有开源发布，我们会尽快按计划推进发布

**Comment by chencyudel** [comment]
@YanqiDai We have released MFTCoder v0.3.0, which includes convergence balance tech via Self-paced Loss
