### ISSUE TITLE
单卡v1000，微调报错

### ISSUE THREAD

**Issue by sxsxsx** [codefuse-ai/MFTCoder#28]

**Comment by twelveand0** [comment]
你好，能否提供更多些GPU卡信号的信息，我不能确定你说的是Nvidia V100还是其他品牌的V1000。关于错误，能否提供更多一些的错误细节，包括exception traceback，启动配置和训练配置。

**Comment by sxsxsx** [comment]
这个可以删掉了，谢谢 问题已经解决
