### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by sxsxsx** [codefuse-ai/MFTCoder#29]
configs/*_train_config中，指定data_paths=['codefuse-aiCodeExercise-Python-27k']，读取CodeExercise-Python-27k.json的时候报错。

data_paths该如何指定呢？具体指的是什么数据集的路径？

万分期待您的回答！🙏

命令行指令如下：
python mft_accelerate.py  --train_config configs/qwen_train_config.json

**Comment by MaoYouSi** [comment]
我的尝试里面，这个data path是指的保存json的文件夹路径，不到具体到json。
这个list里面也不需要加引号' '来着

**Comment by sxsxsx** [comment]
这个路径在代码里面首先会split，然后再读取data path 下的json文件
                fin = open(file_name, 'r')
                for i, line in enumerate(fin):
                    # pre-sharding
                    if shard_data and i % world_size != global_rank:
                        continue
                    data = json.loads(line.rstrip('\n\r'))
                    features, length = encoder.encode(data)
                    # may have more samples
                    for idx in range(len(features['input_ids'])):
                        cur_dataset_input_ids.append(features['input_ids'][idx])
                        cur_dataset_loss_mask.append(features['loss_mask'][idx])


应该是读取train json，然后token。。应该不是存json的文件夹路径吧

**Comment by sxsxsx** [comment]
这个训练你有跑通吗？

**Comment by twelveand0** [comment]
配置data_paths参数时有几点需要注意：
1. 路径写到最后一级文件夹路径，不要写到文件路径
2. 数据文件夹下不要有其他非.jsonl文件，数据集文件命名为.jsonl结尾
3. 如果要指定多个数据集（多任务），不同数据集之间用英文逗号分隔且不要有空格

这是一个多数据配置示例
```
    "data_paths": "[/mnt/data/task1_jsonl_dir,mnt/data/task2_jsonl_dir]",
```

**Comment by sxsxsx** [comment]
已解决 谢谢
