### ISSUE TITLE
no 7B model size?

### ISSUE THREAD

**Issue by zheng5yu9** [codefuse-ai/MFTCoder#30]
what is the reason  for no avaliable  model  less than  7B?    
which  model size in the prod  env ?

**Comment by zheng5yu9** [comment]
infer latency?

**Comment by twelveand0** [comment]
I'm not quite clear on your question yet. Could you provide more details, including the exception stack, startup configuration, and training configuration? MFTCoder does not have specific size restrictions for models that have already been adapted. The currently supported models include llama2, codellama, baichuan, qwen1, chatglm2, among others. Notably, the *codeqwen_competition* branch can support qwen2, which includes both qwen-1.8b and 72b.
