### ISSUE TITLE
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

### ISSUE THREAD

**Issue by sxsxsx** [codefuse-ai/MFTCoder#32]
运行
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
)
tokenizer = AutoTokenizer.from_pretrained(mode_name_or_path, trust_remote_code=True, use_fast=False, legacy=False)
tokenizer.padding_side = "left"
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("<unk>")
tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids("</s>")
model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, trust_remote_code=True)

HUMAN_ROLE_START_TAG = "<|role_start|>human<|role_end|>"
BOT_ROLE_START_TAG = "<|role_start|>bot<|role_end|>"
texts = ["write a python function of quick sort."]
texts = [f"{HUMAN_ROLE_START_TAG}{text}{BOT_ROLE_START_TAG}" for text in texts]

inputs = tokenizer(texts, return_tensors='pt', padding=True, add_special_tokens=False).to("cuda")
outputs = model.generate(
        inputs=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=512,
        top_p=0.95,
        temperature=0.1,
        do_sample=True,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id
    )
gen_text = tokenizer.batch_decode(outputs[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)
print(gen_text)

mode_name_or_path 是 从huggingface 下载的qwen 1_8B，报错

ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

请问该怎么解决？

**Comment by sxsxsx** [comment]
我看了微调的代码，pad_or_end 都是'<|im_end|>'
tokenizer.pad_token_id 和tokenizer.eos_token_id 改为如下 不会报错
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids('<|im_end|>')
tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids('<|im_end|>')

并将 model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, trust_remote_code=True)
改为 model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, revision='master', device_map="auto", trust_remote_code=True).eval()
不改会报device相关错误

可以成功运行，输出结果很奇怪，如下：

['write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|']

**Comment by sxsxsx** [comment]
请问设置tokenizer 还有 HUMAN_ROLE_START_TAG  BOT_ROLE_START_TAG的作用是什么

**Comment by twelveand0** [comment]
> 运行 from transformers import ( AutoTokenizer, AutoModelForCausalLM, ) tokenizer = AutoTokenizer.from_pretrained(mode_name_or_path, trust_remote_code=True, use_fast=False, legacy=False) tokenizer.padding_side = "left" tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("") tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids("") model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, trust_remote_code=True)
> 
> HUMAN_ROLE_START_TAG = "<|role_start|>human<|role_end|>" BOT_ROLE_START_TAG = "<|role_start|>bot<|role_end|>" texts = ["write a python function of quick sort."] texts = [f"{HUMAN_ROLE_START_TAG}{text}{BOT_ROLE_START_TAG}" for text in texts]
> 
> inputs = tokenizer(texts, return_tensors='pt', padding=True, add_special_tokens=False).to("cuda") outputs = model.generate( inputs=inputs["input_ids"], attention_mask=inputs["attention_mask"], max_new_tokens=512, top_p=0.95, temperature=0.1, do_sample=True, eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.pad_token_id ) gen_text = tokenizer.batch_decode(outputs[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True) print(gen_text)
> 
> mode_name_or_path 是 从huggingface 下载的qwen 1_8B，报错
> 
> ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
> 
> 请问该怎么解决？
可以这样设置：
```python
tokenizer = AutoTokenizer.from_pretrained(mode_name_or_path, trust_remote_code=True, use_fast=False, legacy=False)
tokenizer.padding_side = "left"
tokenizer.eos_token = '<|im_end|>' # 如果是其他模型请相应换做其他模型的eos token （可在模型文件夹下的config.json文件中找到）
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids(tokenizer.pad_token)
tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids(tokenizer.eos_token)
```

**Comment by twelveand0** [comment]
> 我看了微调的代码，pad_or_end 都是'<|im_end|>' tokenizer.pad_token_id 和tokenizer.eos_token_id 改为如下 不会报错 tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids('<|im_end|>') tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids('<|im_end|>')
> 
> 并将 model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, trust_remote_code=True) 改为 model = AutoModelForCausalLM.from_pretrained(mode_name_or_path, revision='master', device_map="auto", trust_remote_code=True).eval() 不改会报device相关错误
> 
> 可以成功运行，输出结果很奇怪，如下：
> 
> ['write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|>bot<|role_end|>write a python function of quick sort.<|role_start|']
如果你是用codeqwen-competition分支微调的Qwen-1.8B模型，微调使用的格式与master分支不同，因此推理时需要用下面的格式:
```
<|im_start|>user
Write a quick sort python program<|im_end|>
<|im_start|>assistant

```
从你的输出看，你使用的推理格式是master分支中写的格式，这与codeqwen-competition分支使用的微调数据格式不同

**Comment by twelveand0** [comment]
> 请问设置tokenizer 还有 HUMAN_ROLE_START_TAG BOT_ROLE_START_TAG的作用是什么

1. 推理时设置 HUMAN_ROLE_START_TAG和BOT_ROLE_START_TAG的目的为了与微调训练使用的数据格式（tokenization数据格式）一致，这样才能最大发挥出微调后的模型效果；至于在微调训练中设置这些TAGs的目的主要是为了使模型能支持多轮会话，使得在多轮会话中能区分出哪个是Human问的、哪个是BOT/Model回答的
2. 推理设置tokenizer eos_token相当于设置一个推理结束符，使得模型能知道什么时候推理生成结束（在无长度限制条件下，即遇到eos_token的时候）；设置pad_token是为了应对推理batch > 1的情形，batch>1时由于不同问题的长度很多时候是不同的（即token数量不同），模型实际接收的是一个矩阵（一个元素是一个token），这时需要用pad token把短的问题给补齐，使得同一个batch内的每个问题都是等长的。你可能会担心这些添加的pad token会影响原问题推理，实际上你不需要担心，在实际推理时由于会有mask attention存在，mask attention会将这些pad位置设置为0，因此这些额外增加的pad token不会参与实际的推理生成而不会影响原来的生成。

**Comment by sxsxsx** [comment]
好的，多谢 多谢

**Comment by twelveand0** [comment]
I closed this issue. You can reopen it if you have more questions.

**Comment by sxsxsx** [comment]
我在model目录下的配置文件中没有找到pad_token 的配置，请问pad_token 是默认等于eos_token吗？他们不应该是要区分开吗？
tokenizer.eos_token = '<|im_end|>' # 如果是其他模型请相应换做其他模型的eos token （可在模型文件夹下的config.json文件中找到）
tokenizer.pad_token = tokenizer.eos_token

**Comment by twelveand0** [comment]
> 我在model目录下的配置文件中没有找到pad_token 的配置，请问pad_token 是默认等于eos_token吗？他们不应该是要区分开吗？ tokenizer.eos_token = '<|im_end|>' # 如果是其他模型请相应换做其他模型的eos token （可在模型文件夹下的config.json文件中找到） tokenizer.pad_token = tokenizer.eos_token

```pad_token```在model/config.json里没有，如果你用了```batch>1```需要专门设置，默认不等于```eos_token```，```pad_token```只是用于batch内size对齐，不参与实际的loss计算或推理，理论上```pad_token```可以是任意一个token，设置等于```eos_token```只是为了方便。
