### ISSUE TITLE
请问要支持chatglm3-6b-base的话需要哪些更改

### ISSUE THREAD

**Issue by kevindany** [codefuse-ai/MFTCoder#35]
找到MFT的方法非常高兴，感谢开源！我目前在基于chatglm3的base model做意图识别和实体抽取的任务的sft，请教下：
1. chatglm2的实测效果如何，针对单任务样本，分批次进行sft和采用MFT的方法的效果差别有多大？从准确率和幻觉方面有什么数据参考吗？
2. chatglm3如果要做MFT，有哪些需要修改？新增configs下的配置之后，还有什么需要修改的吗？

感谢！

**Comment by chencyudel** [comment]
@kevindany hello, we are not sure how chatglm3 performs in all tasks, however we can offer some experience:
1. MFTCoder v0.3.0 is going to be released these days, it supports chatglm3, so you could try SFT/MFT, please refer to [MFTCoder-accelerate](https://github.com/codefuse-ai/MFTCoder/blob/main/mftcoder_accelerate/README_cn.md) for the details of training and configs.
2. Sequential SFT is different from MFT, MFT is trying to balance each task via different loss mode thus MFT is a trade-off for multiple tasks. While sequential SFT is something like curriculum learning which may suffer from Catastrophic forgetting（need to be solved).

**Comment by kevindany** [comment]
Very glad to hear from you, very appreicate it!
