### ISSUE TITLE
数据集loss 下降不均衡如何处理

### ISSUE THREAD

**Issue by huangmenglong** [codefuse-ai/MFTCoder#55]
您好， 请教一下 
      在多任务训练中， 有的任务loss已经过拟合了 其他任务还在loss下降， 这种如何处理呢， 当前主动训练中止时某数据集严重过拟合

**Comment by GoneZ5** [comment]
您好，请问是指valid loss出现这种情况吗，如果是的话，可以尝试使用最新更新的收敛均衡方法动态调整各任务的权重：
- 把``weighted_loss_mode``设置成``selfpaced``
- ``selfpaced_history_length``设置成大约5倍的valid dataloader batch数（5 * len(valid_dataloader)），注意不是batch size
- ``selfpaced_scale_factor``根据需求设置，越大则各任务权重之间的差别越大，可以先采用默认值
