### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by lwh8915** [codefuse-ai/MFTCoder#57]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

问下我在使用qlora微调时报这个错误是什么意思

**Comment by chencyudel** [comment]
We have just released v0.4.2, QLoRA is now supported by Deepspeed Zero stage 2 or Zero stage 3, while Lora is only supported by Zero2. The older version
