### ISSUE TITLE
基于chatgpt生成的高质量python练习题数据是如何获取呀

### ISSUE THREAD

**Issue by 18liumin** [codefuse-ai/MFTCoder#6]

**Comment by twelveand0** [comment]
如果你是想使用我们发布的数据集，可以通过这个地址获取：[CodeFuse-CodeExercises-Python](https://modelscope.cn/datasets/codefuse-ai/CodeExercise-Python-27k/summary )

如果你是想自己构建，可以参考我们文章里的简要介绍 [MFTCoder paper (preprint)](https://arxiv.org/abs/2311.02303)
